name: Automated Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build SASS
        run: npm run build

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Test lint
        run: npm run lint

      - name: Run Jest Unit Tests
        run: npm run test-unit

      - name: Run Cypress E2E Tests (CLI)
        run: npm run test-e2e-cli
